### ISSUE TITLE
Has anyone succeeded in unity 2020?

### ISSUE THREAD

**Issue by shoukailiang** [qian256/HoloLensARToolKit#67]
Has anyone succeeded in unity 2020?

**Comment by USTBVEO** [comment]
I tried to build on Hololens but it turned to the error : Assets\ARToolKitUWP\Scripts\ARUWPVideo.cs(723,20): error CS0103: The name 'WorldManager' does not exist in the current context
![image](https://user-images.githubusercontent.com/50726335/162719910-9518b9cb-5b2c-4561-807b-d90870b64087.png)
I searched and find that 'WorldManager' doesn't exist in Unity 2020.3.
![image](https://user-images.githubusercontent.com/50726335/162720145-59479fb3-6f00-4cbb-8305-1bf6e060c53e.png)

**Comment by petergu684** [comment]
In Unity 2020 (and all other versions using XRSDK), replace the line with following:
```cs
 WorldOriginPtr = UnityEngine.XR.WindowsMR.WindowsMREnvironment.OriginSpatialCoordinateSystem;
```
PS: It won't work in Unity 2021.2 or later where OpenXR is the only supported pipeline.

**Comment by USTBVEO** [comment]
> In Unity 2020 (and all other versions using XRSDK), replace the line with following:
> 
> ```cs
>  WorldOriginPtr = UnityEngine.XR.WindowsMR.WindowsMREnvironment.OriginSpatialCoordinateSystem;
> ```
> 
> PS: It won't work in Unity 2021.2 or later where OpenXR is the only supported pipeline.

Thanks and I did that where I found that the hologram moved as I turned around my head. The hologram was not set to a fixed position. How can I tackle this problem? Thanks a lot!
